services:
  flask:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ../.env
      - .env
    volumes:
      - ..:/app
    depends_on:
      - redis
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  redis:
    image: redis:latest
    environment:
      - TZ=Europe/Madrid
    env_file:
      - .env
    ports:
      - "${REDIS_EXPOSE_PORT}:6379"
    volumes:
      - redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DB_EXPOSE_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_HOST=database
    ports:
      - "${PHPMYADMIN_EXPOSE_PORT}:80"
    env_file:
      - .env
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

volumes:
  redis-data:
  db-data:
