services:
  parking_flask:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ../.env
      - .env
    volumes:
      - ..:/app
    depends_on:
      - redis
      - database
    restart: always

  parking_redis:
    image: redis:latest
    container_name: redis
    environment:
      - TZ=Europe/Madrid
    env_file:
      - .env
    ports:
      - "${REDIS_EXPOSE_PORT}:6379"
    volumes:
      - redis-data:/data
    restart: always

  parking_database:
    image: mysql:5.7
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DB_EXPOSE_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    
  parking_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_HOST=database
    ports:
      - "${PHPMYADMIN_EXPOSE_PORT}:80"
    env_file:
      - .env
    depends_on:
      - database
    restart: always

volumes:
  redis-data:
  db-data:
